language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

virtualenv:
  system_site_packages: true

install:
  - "python -m venv venv"
  - "pip install -r https://github.com/abhijeetraj22/Quiz_Systems/blob/master/requirements.txt"

script:
  - venv/bin/activate
  - python __init__.py
